runtime: custom
service: link-up
env: flex
threadsafe: true
zones:
- us-east1-b
- us-east1-c
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
network:
  session_affinity: true
automatic_scaling:
  max_num_instances: 2
env_variables:
  ROOT_URL: https://ProtestBuddy.appspot.com
  MONGO_URL: mongodb+srv://arslanr:hackTest20@cluster0.rbdff.mongodb.net/Hack20?retryWrites=true&w=majority
  MAIL_URL:
skip_files:
  - ^(.*/)?\.dockerignore$
  - ^(.*/)?\npm-debug.log$
  - ^(.*/)?\\yarn-error.log$
  - ^(.*/)?\.git$
  - ^(.*/)?\.hg$
  - ^(.*/)?\.svn$
  
